services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=roomReservation
      - DB_USER=root
      - DB_PASS=MySQLPassword
    depends_on:
      - db
    networks:
      - room_reservation_network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - room_reservation_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySQLPassword
      MYSQL_DATABASE: roomReservation
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
        - room_reservation_network

volumes:
  db_data:

networks:
  room_reservation_network:
        driver: bridge